name: Lint

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  packer-validate:
    runs-on: ubuntu-latest
    name: packer-validate
    env:
      PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Packer 1.9.5
        uses: hashicorp-contrib/setup-packer@v3
        with:
          packer-version: 1.9.5
      - name: Init Packer
        run: packer init .
        working-directory: packer
      - name: Validate Packer
        run: packer validate -syntax-only .
        working-directory: packer

  terraform-fmt:
    runs-on: ubuntu-latest
    name: terraform-fmt
    steps:
      - uses: actions/checkout@v4
      - name: Use Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      - name: Check formatting
        run: terraform fmt -check -recursive .

  terraform-validate:
    runs-on: ubuntu-latest
    name: terraform-validate
    strategy:
      matrix:
        module:
          - modules/ec2-teleport-agent-pool
          - modules/teleport-kube-agent
    steps:
      - uses: actions/checkout@v4
      - name: Use Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      - name: Init
        run: terraform init -backend=false
        working-directory: ${{ matrix.module }}
      - name: Validate
        run: terraform validate
        working-directory: ${{ matrix.module }}

  shellcheck:
    runs-on: ubuntu-latest
    name: shellcheck
    steps:
      - uses: actions/checkout@v4
      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './packer/scripts'
          severity: warning
