name: Test Teleport Agent AMI

on:
  pull_request:
    paths:
      - 'packer/**'
      - 'modules/**'
      - 'test/**'
      - '.github/workflows/pr-test.yml'

env:
  PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  packer_build:
    strategy:
      matrix:
        architecture: ['arm64']
    runs-on: ubuntu-latest
    name: e2e-test-teleport-agent
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_E2E }}

      - name: Use Packer 1.9.5
        uses: hashicorp-contrib/setup-packer@v3
        with:
          packer-version: 1.9.5

      - name: Use Terraform 1.5.7
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
          terraform_wrapper: false

      - uses: actions/setup-go@v5
        with:
          go-version-file: test/go.mod
          cache-dependency-path: test/go.sum

      - name: Use Teleport 18.6.8
        uses: teleport-actions/setup@v1
        with:
          version: 18.6.8

      - name: Init Packer template
        run: packer init .
        working-directory: packer

      - name: Validate Packer template
        run: packer validate -syntax-only .
        env:
          PKR_VAR_architecture: ${{ matrix.architecture }}
        working-directory: packer

      - name: Setup test environment
        run: make setup
        working-directory: test

      - name: Run e2e tests
        run: go test -v -timeout 30m
        working-directory: test
